### ISSUE TITLE
Any docker-compose file for this tool?

### ISSUE THREAD

**Issue by jlgarnier** [Angatar/mailman2#5]
Hi all,

I'm looking for an example docker-compose file to deploy a test instance of this tool (I'm *really* not a Docker expert): would anyone mind sharing one?

Thanks in advance for any help!

**Comment by Angatar** [comment]
Hi,
You can start with the following example as a basis for your compose.yaml file and adapt it according to the documentation and your requirements. Please note that even for a test you will need to add the proper DNS records for your domain to make it works.
```
services:
  mailman:
    image: d3fk/mailman2
    container_name: mailman
    hostname: ${EMAIL_HOST}
    restart: always
    ports:
      - "80:80"
      - "25:25"
      - "465:465"
    environment:
      EMAIL_HOST: ${EMAIL_HOST}
      URL_HOST: ${URL_HOST}
      LIST_ADMIN: ${LIST_ADMIN}
      MASTER_PASSWORD: ${MASTER_PASSWORD}
      URL_PATTERN: ${URL_PATTERN}
      URL_ROOT: ${URL_ROOT}
    extra_hosts:
      - ${EMAIL_HOST}:127.0.0.1
```

You can replace the env vars by your values in the compose.yaml or create in the same directory a [.env](https://docs.docker.com/compose/environment-variables/) file that will be easier to maintain e.g.:
.env
```
URL_HOST=lists.example.com
EMAIL_HOST=mails.example.com
LIST_ADMIN=youremail@example.com
MASTER_PASSWORD=example
URL_PATTERN=http
URL_ROOT=lists/
```
You can complete the compose.yaml and .env with environment variables listed in the [ENVIRONMENT section](https://github.com/Angatar/mailman2#environment)

Then simply run your compose file with ```docker-compose up -d``` and visit your $URL_HOST/$URL_ROOT/admin to start managing your mailing lists (indicate the mapped port after the URL_HOST if required). 

Hope this helps.
